### ISSUE TITLE
Condition(s) de terminaison du jeu

### ISSUE THREAD

**Issue by Romain96** [Romain96/JeuxEtStrategies#1]
Trouver un moyen d'arrêter tous les agents à la fin du jeu
Trouver un moyen d'arrêter tous les producteurs à la fin du jeu
Trouver un moyen d'arrêter le coordinateur

**Comment by Dawguie** [comment]
Maintenant que j'y pense on a pas forcement besoin "d’arrêter" les agent. Peut être qu il ne faut seulement que les réinitialiser. Pense s'y; a la fin d'un jeux le programme s’arrête pas il est plutôt en mode "GameOver/PlayAgain". Du coup on arrêterait les agent en fermant la fenêtre du jeux.. bon après c'est pas très propre. Mais du coup pour le coordinateur il peut etre ne rien faire jusqu’à qu'on lui dise de faire une nouvel partie (en spécifiant a nouveau le nb de joueur etc..) ou qu'on le ferme. Ca ajouterait un état a la machine qu il faudra gérer par contre. Dit moi si tu comprend pas, j'ai écrit un pavé xD

**Comment by Romain96** [comment]
Il faut qu'on y réfléchisse mais ce n'est pas la priorité pour l'instant.
ça semble fonctionner avec plusieurs agents donc le projet avance bien :)

**Comment by Dawguie** [comment]
Ouai j'ais vue :D

**Comment by Romain96** [comment]
Presque résolu (ne fonctionne pas pour tous les agents mais fonctionne pour tous les producteurs)
Projet officiellement terminé [2017-05-01], fermeture de l'issue
