### ISSUE TITLE
Interface graphique

### ISSUE THREAD

**Issue by Romain96** [Romain96/JeuxEtStrategies#2]
Trouver un moyen de garder un historique des actions réalisées par chacun
Trouver un modèle existant de représentation graphique
Trouver un moyen de représenter les actions (ressources principalement) dans l'interface graphique

**Comment by Romain96** [comment]
[à valider] Pour l'historique :
chaque agent/producteur/coordinateur remplit un fichier csv qu'il crée lui-même au lancement et l'interface graphique récupère le contenu de chaque historique pour réaliser l'affichage.

**Comment by Dawguie** [comment]
Je pense que le seul problème d'avoir n fichier svn pour les n agent/produc/coord c'est que sa en fait beaucoup. On pourrait: 
   - en avoir que 1 dans le coordinateur ou tout le monde écrit quand s'est leur tour
   - ou tout le monde en a un et quand s'est leur tour il copient ce qui est dans le coordinateur puis écrivent leur action.

Comme sa on a besoin que de 1 fichier csv a la fin. Mais je sais pas si tout mon truc finira par être plus compliqué que simplement traité les n fichiers.

**Comment by Romain96** [comment]
Oui on pourrait faire en sorte que la fonction signalerFinTour transmette aussi le nombre de ressources actuelles pour chaque agent. 
Du coup on aurait quelque chose de la forme : 
public void signalerFinTour(int idAgent, Ressource ressources)
et donc seul le coordinateur tiendrait un fichier de log à jour à chaque fin de tour de chaque agent (1 ligne à chaque fois)

**Comment by Romain96** [comment]
Gnuplot en mettant en x le numéro du tour de jeu et en y la somme des ressources possédées.
On obtient donc une courbe par agent.
Projet officiellement terminé [2017-05-01], fermeture de l'issue
